"""add cfg pdg verdict columns

Revision ID: 86a63c7a7133
Revises: 370dda2f1259
Create Date: 2026-04-26 19:27:58.381565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a63c7a7133'
down_revision: Union[str, None] = '370dda2f1259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('cfg_score', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('results', sa.Column('pdg_score', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('results', sa.Column('verdict', sa.String(), nullable=False, server_default='Unknown'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'verdict')
    op.drop_column('results', 'pdg_score')
    op.drop_column('results', 'cfg_score')
    # ### end Alembic commands ###
